### ISSUE TITLE
Difference between OpenUnReID and the original MMT's implementation

### ISSUE THREAD

**Issue by RAMIhamza** [open-mmlab/OpenUnReID#33]
Hello,
I have already noticed that in this implementation, MMT does not require any pre-training on source domain. I wonder if there are any other slight differences between OpenUnReID's implementation and the one proposed by the original autors. 
Many thanks,

**Comment by yxgeee** [comment]
As you mentioned that the MMT in OpenUnReID is trained in only one phase, so domain-specific BNs are used in the network to enable jointly training with different domains' images. Also, some results in MODEL_ZOO adopted GeM pooling instead of the original average pooling for boosting the performance.

**Comment by RAMIhamza** [comment]
Thank you so much !
